import { Lato } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/home/header";

// const inter = Inter({
//   subsets: ["latin"],
// });

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${inter.className} antialiased`}> */}
      <body className={`${lato.className} antialiased`}>


        <Header />

        {children}

        <Footer />

      </body>
    </html>
  );
}
